### ISSUE TITLE
peek method

### ISSUE THREAD

**Issue by xlc** [gh123man/Async-Channels#12]
Can we have a `func peek<R>(fn: (inout T) - R) async` method that allow me to inspect and potentially modify the next element (and await if needed) without receive it?

Use case: I am working with a networking library and it essentially I am sending `Data` to the channel. I sometimes need to receive a single byte instead of a Data chunk. It will be too inefficient to make `UInt8` channel. But when I received a Data, I can't only take a single byte and put the rest back to the head of the queue. Right now I need to maintain another buffer for this purpose and makes the code more complicated.

Happy to make a PR if needed.

**Comment by gh123man** [comment]
While I think this could be implemented conceptually. It disagrees with the design principals of a channel implementation. By allowing data to be mutated on the buffer, the contract between the sender and receiver can be broken. 

Additionally in cases where there are many receivers, using such a function could cause unpredictable behavior. 

However I am happy to help you come up with a cleaner implementation giving the problem you are facing. 
Are you able to share a simple example demonstrating (or describe in more detail) the data flow and how you are trying to mutate it? Do you have multiple threads reading/writing to this data? 

Perhaps using a ring buffer or similar data structure would be more appropriate?

**Comment by xlc** [comment]
The mutation should be protected by locks so I don't see how it could cause unpredictable behavior.

This is my code:

```swift
public final class Stream: Sendable {
    let stream: QuicStream
    private let channel: Channel<Data> = .init(capacity: 100)
    private let nextData: ThreadSafeContainer<Data?> = .init(nil)
    private let _status: ThreadSafeContainer<StreamStatus> = .init(.open)

    public private(set) var status: StreamStatus {
        get {
            _status.value
        }
        set {
            _status.value = newValue
        }
    }

    init(_ stream: QuicStream) {
        self.stream = stream
    }

    public func send(data: Data) throws {
        guard status == .open else {
            throw StreamError.notOpen
        }
        try stream.send(data: data)
    }

    func received(data: Data) -> Bool { // got some data
        if data.isEmpty {
            return true
        }
        Task {
            await channel.send(data)
        }
        // return false if channel is full
    }

    func close() { // stream is closed gracefully
        status = .closed
        channel.close()
    }

    func abort() { // stream is aborted with some error
        status = .aborted
        channel.close()
    }

    public func receive() async -> Data? {
        if let data = nextData.exchange(nil) {
            return data
        }
        return await channel.receive()
    }

    public func receiveByte() async -> UInt8? {
        // this method isn't exactly right and can have races
        if var data = nextData.value {
            let byte = data.removeFirst()
            if data.isEmpty {
                nextData.value = nil
            } else {
                nextData.value = data
            }
            return byte
        }

        guard var data = await receive() else {
            return nil
        }

        let byte = data.removeFirst()
        if !data.isEmpty {
            // this could append the data in wrong order
            nextData.write { nextData in
                if let currentData = nextData {
                    nextData = currentData + data
                } else {
                    nextData = data
                }
            }
        }
        return byte
    }
}
```

and

```swift
let byte = await stream.receiveByte()
let processor = getProcessor(type: byte) // determine the data type from byte
processor.process(stream) // loop call stream.receiveData() and process the data until the stream is closed
```

`ThreadSafeContainer` is a RWLock protected box

`receiveByte` is the method that is currently hard to implement correctly. It is fine if there is only a single reader but otherwise not.

**Comment by gh123man** [comment]
If you expect to have multiple consumers of `receiveByte` and deal with shared state (`nextData`). Perhaps `Stream` should be an actor instead of a class? If this doesn't work you could use a simple mutex to protect the whole `receiveByte` function. I expect the race issues in `receiveByte` are due to granular locking of `nextData`. 

This would also allow you to store just a native `Data` without having to wrap it in a container and simplify the code.

**Comment by xlc** [comment]
I don't want to make Stream an actor because that will make all the methods asyn and many of them are used in C callbacks and can't be async.

Yeah a big mutex will work.
