### ISSUE TITLE
Would it be possible to add buildEither to SelectCollector?

### ISSUE THREAD

**Issue by Kuniwak** [gh123man/Async-Channels#8]
Hello,

I would like to discuss the possibility of accepting a PR to add the `buildEither` method to [`SelectCollector`](https://github.com/gh123man/Async-Channels/blob/394b971c97376c4b3dddf1683c1547912cd28a00/Sources/AsyncChannels/Select.swift#L84-L89).

The use case I am about to explain is quite specialized, and I acknowledge that almost no one else using this library, except for me, may ever need this functionality.

I am a developer trying to create a [CSP](https://en.wikipedia.org/wiki/Communicating_sequential_processes) library in Swift similar to [JCSP](https://github.com/CSPforJAVA/jcsp). JCSP is a library that implements some CSP functionalities in Java. One of the features of CSP is external choice, which allows the selection of channels that can either send or receive messages. I plan to use `select` for selecting channels that can send or receive messages. However, in implementing this external choice, using Async-Channel gives too much flexibility, making verification difficult. Therefore, I plan to publish the following code with restrictions to reduce this flexibility:

```swift
public indirect enum Process<Ev: Hashable, Value> {
    // ...
    case externalChoice([ChannelID: ChannelHandler<Ev, Value>])
    // ...
}

public enum ChannelHandler<Ev: Hashable, Value> {
    case receive((Value) -> Process<Ev, Value>)
    case send(Value, Process<Ev, Value>)
}

public func interpret<Ev: Hashable, Value>(process: Process<Ev, Value>, onContext context: Context<Ev, Value>) async throws {
    switch process {
    // ...
    case .externalChoice(let events, let channels):
        let channels = channels.map { (channel: context.channelMap[$0.key]!, handler: $0.value) }
        var nextProcess: Process<Ev, Value>? = nil
        await select {
            any(channels) { entry in
                let channel = entry.channel
                let handler = entry.handler
                
                switch handler { // This line causes an error because SelectCollector does not have buildEither
                case .receive(let fn):
                    receive(channel) { value in
                        nextProcess = fn(value!)
                    }
                case .send(let value, let process):
                    send(value, to: channel) {
                        nextProcess = process
                    }
                }
            }
            try await interpret(process: nextProcess!, onContext: context)
        }
```

This code encounters an error because there is a switch statement inside the `select`, and `SelectCollector` does not have the `buildEither` method. Therefore, would it be possible to add `buildEither` to `SelectCollector`?

If you are open to this addition, I will prepare a PR. I would appreciate your feedback on this matter.

**Comment by gh123man** [comment]
Are there any possible drawbacks to implementing `buildEither` (changes/breakage to the existing API)? From a surface look I can't see any - so with that in mind I would be in favor of adding support for this. I am happy to review and test the PR.

**Comment by Kuniwak** [comment]
> Are there any possible drawbacks to implementing `buildEither` (changes/breakage to the existing API)? From a surface look, I can't see any

I agree. Based on my reading of [SE-0289](https://github.com/swiftlang/swift-evolution/blob/70499c5ee1cb4d70653952607501390b67215c39/proposals/0289-result-builders.md), adding the `buildEither` method seems to be a purely additive change because it only increases the syntax available within the `resultBuilder`. The `SelectHandler` generated by the existing syntax remains unchanged. Therefore, I believe the behavior of `select` statements that did not previously cause compilation errors will not be affected by the addition of the `buildEither` method.

**Comment by Kuniwak** [comment]
I sent a pull request about it at #10.
